### PR TITLE
Drop the python bindings, move to tools/ratbagctl

### PR DESCRIPTION
**Pull request by whot**
The diff looks a bit stranger than need be but the first commit removes the python/__init__.py and moves its contents to ratbagctl. That is also moved to tools/ in the process. Only code change beyond that is to drop the import ratbagd statement

### CODE REVIEW

**Comment by whot** [comment]
CC @Hjdskes, this will break piper once merged

**Review by bentiss — APPROVED** [review]
Works for me

**Comment by bentiss** [comment]
@Hjdskes it'll break piper, but until piper is fixed, you can always rely on the currently realeased 0.4 version on ratbagd. Thus the accepted review.

**Comment by Hjdskes** [comment]
I'll copy the bindings into Piper as suggested by @whot, assuming we don't care about the duplication?

**Comment by bentiss** [comment]
> assuming we don't care about the duplication?

currently no. If we realize that there is a strong need, we can always add a new python-ratbagd project with just the bindings. But you might as well duplicate the code in a first step, and then rewrite the binding to your needs in piper.

**Pull request merged**
